schema_version: 1

context:
  name: dtoolai
  version: 0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dtoolai-${{ version }}.tar.gz
  sha256: eb66acdee560d18242cbdfcc5aa9d078021c84bb13677fb1574c2ad06e71b3ac

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }}  -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dtoolai-provenance = dtoolai.utils:print_provenance
      - create-image-dataset-from-dirtree = dtoolai.utils:image_dataset_from_dirtree_cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - click
    - dtool_http
    - dtoolcore
    - pillow
    - python >=${{ python_min }}
    - pytorch
    - torchvision

tests:
  - python:
      imports:
        - dtoolai
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - dtoolai-provenance --help
      - create-image-dataset-from-dirtree --help

about:
  license: MIT
  license_file: LICENSE
  summary: Dtool AI reproducible AI library
  description: dtoolAI is a library for supporting reproducible deep learning.
  homepage: http://github.com/JIC-CSB/dtoolai
  repository: http://github.com/JIC-CSB/dtoolai
  documentation: http://github.com/JIC-CSB/dtoolai

extra:
  recipe-maintainers:
    - jan-janssen
